"""Group family g12 -- "reflection / symmetric completion".

Concept: PLANE MIRROR (optics) -- image formation by plane mirrors.
Every object point P in front of a mirror has a virtual image P' on the mirror's normal through P,
at the same distance behind the mirror.  The output = input + the images of the object(s) (painted only
on empty background), optionally with the object-image normal drawn ("ray", dotted on the pattern's lattice)
for the mirror nearest to the point.

Everything is induced from the task's own training pairs; the only knobs are small finite domains:
  placement  : 'grid'   -- mirrors on the grid's central axes, group in {V, H, VH, D4(square only)}
               'line'   -- a full-length uniform row/column drawn in the grid is the mirror
               'object' -- one mirror per object (8-connected component), on the axis in which the object
                           is NOT mirror-symmetric, parallel to its bounding box, on side in {flat, bump}
                           (flat = the extreme line with more cells), gap to the image in {0,1,2}
  colour     : 'same'  (image keeps the object colour) | 'axis' (one colour per mirror axis, read from train)
  ray        : None | lattice step in {1,2}: connect each point to its image in its strictly nearest
               axis-parallel mirror (ties = no ray), cells spaced by the step.
Rejects anything whose outputs are not same-size supersets of the inputs.
"""
from collections import Counter


# ---------------------------------------------------------------- helpers
def _bg(train):
    return Counter(v for p in train for row in p['input'] for v in row).most_common(1)[0][0]


def _components(g, bg, skip=frozenset()):
    H, W = len(g), len(g[0]); seen = set(skip); comps = []
    for r in range(H):
        for c in range(W):
            if g[r][c] != bg and (r, c) not in seen:
                seen.add((r, c)); st = [(r, c)]; cells = []
                while st:
                    y, x = st.pop(); cells.append((y, x))
                    for dy in (-1, 0, 1):
                        for dx in (-1, 0, 1):
                            q = (y + dy, x + dx)
                            if 0 <= q[0] < H and 0 <= q[1] < W and q not in seen and g[q[0]][q[1]] != bg:
                                seen.add(q); st.append(q)
                comps.append(cells)
    return comps


def _reflect(p, m):
    """mirror m = (axis, k): 'v' vertical line (c -> k-c), 'h' horizontal line (r -> k-r),
    't' main diagonal (r,c)->(c,r), 'a' anti-diagonal (r,c)->(k-c,k-r).  k is a doubled coordinate."""
    ax, k = m; r, c = p
    if ax == 'v': return (r, k - c)
    if ax == 'h': return (k - r, c)
    if ax == 't': return (c, r)
    return (k - c, k - r)


def _orbit(p, mirrors):
    """all images of p under the group generated by the mirrors, with the first mirror label reaching it"""
    orb = {p: None}; st = [p]
    while st:
        q = st.pop()
        for m in mirrors:
            q2 = _reflect(q, m)
            if q2 not in orb:
                orb[q2] = orb[q] or m[0]; st.append(q2)
    return orb


def _is_sym(cells, g, m):
    s = set(cells)
    return all(_reflect(p, m) in s and g[p[0]][p[1]] == g[_reflect(p, m)[0]][_reflect(p, m)[1]] for p in cells)


# ---------------------------------------------------------------- mirror placements
def _units_grid(g, bg, group):
    H, W = len(g), len(g[0])
    cells = [(r, c) for r in range(H) for c in range(W) if g[r][c] != bg]
    ms = {'V': [('v', W - 1)], 'H': [('h', H - 1)], 'VH': [('v', W - 1), ('h', H - 1)],
          'D4': [('v', W - 1), ('h', H - 1), ('t', 0)]}[group]
    if group == 'D4' and H != W:
        return None
    return [(cells, ms)] if cells else []


def _units_line(g, bg, _):
    H, W = len(g), len(g[0])
    ms, line = [], set()
    for r in range(H):
        if g[r][0] != bg and len(set(g[r])) == 1:
            ms.append(('h', 2 * r)); line |= {(r, c) for c in range(W)}
    for c in range(W):
        col = {g[r][c] for r in range(H)}
        if g[0][c] != bg and len(col) == 1:
            ms.append(('v', 2 * c)); line |= {(r, c) for r in range(H)}
    if not ms:
        return None
    cells = [(r, c) for r in range(H) for c in range(W) if g[r][c] != bg and (r, c) not in line]
    return [(cells, ms)]


def _units_object(g, bg, prm):
    side, gap = prm
    units = []
    for cells in _components(g, bg):
        rs = [p[0] for p in cells]; cs = [p[1] for p in cells]
        r0, r1, c0, c1 = min(rs), max(rs), min(cs), max(cs)
        symv = _is_sym(cells, g, ('v', c0 + c1)); symh = _is_sym(cells, g, ('h', r0 + r1))
        if symv == symh:                      # symmetric both ways, or no single asymmetric axis
            continue
        if not symv:                          # asymmetric left/right -> vertical mirror beside it
            n_lo, n_hi = cs.count(c0), cs.count(c1)
            if n_lo == n_hi: continue
            hi = (n_hi > n_lo) == (side == 'flat')
            m = ('v', 2 * c1 + 1 + gap) if hi else ('v', 2 * c0 - 1 - gap)
        else:                                 # asymmetric up/down -> horizontal mirror beside it
            n_lo, n_hi = rs.count(r0), rs.count(r1)
            if n_lo == n_hi: continue
            hi = (n_hi > n_lo) == (side == 'flat')
            m = ('h', 2 * r1 + 1 + gap) if hi else ('h', 2 * r0 - 1 - gap)
        units.append((cells, [m]))
    return units


PLACEMENTS = ([('grid', _units_grid, gr) for gr in ('V', 'H', 'VH', 'D4')]
              + [('line', _units_line, None)]
              + [('object', _units_object, (sd, gp)) for sd in ('flat', 'bump') for gp in (1, 0, 2)])


# ---------------------------------------------------------------- image formation
def _paints(g, bg, units, ray):
    """list of ((r,c), source colour, axis label) in painting order: images first, then rays"""
    H, W = len(g), len(g[0]); out = []
    for cells, ms in units:
        for p in cells:
            for q, lab in _orbit(p, ms).items():
                if lab and 0 <= q[0] < H and 0 <= q[1] < W:
                    out.append((q, g[p[0]][p[1]], lab))
    if ray:
        for cells, ms in units:
            ax = [m for m in ms if m[0] in 'vh']
            if not ax: continue
            for p in cells:
                col = g[p[0]][p[1]]
                for q in _orbit(p, ms):
                    d = sorted((abs(2 * (q[1] if m[0] == 'v' else q[0]) - m[1]), m) for m in ax)
                    if len(d) > 1 and d[0][0] == d[1][0]: continue
                    dist, m = d[0]
                    if dist == 0: continue
                    q2 = _reflect(q, m); i = 1 if m[0] == 'v' else 0
                    step = ray if q2[i] > q[i] else -ray
                    x = list(q)
                    while (x[i] - q2[i]) * step < 0:
                        x[i] += step
                        if 0 <= x[0] < H and 0 <= x[1] < W:
                            out.append((tuple(x), col, m[0]))
    return out


def _render(g, bg, units, ray, cmap):
    o = [row[:] for row in g]; done = set()
    for (r, c), col, lab in _paints(g, bg, units, ray):
        if g[r][c] != bg or (r, c) in done:
            continue
        o[r][c] = col if cmap is None else cmap.get(lab, col); done.add((r, c))
    return o


def fam_plane_mirror(train):
    if not train: return
    for p in train:
        if len(p['input']) != len(p['output']) or len(p['input'][0]) != len(p['output'][0]):
            return
    bg = _bg(train)
    # completion only adds: every non-background input cell survives unchanged
    for p in train:
        for a, b in zip(p['input'], p['output']):
            if any(x != bg and x != y for x, y in zip(a, b)):
                return
    for kind, place, prm in PLACEMENTS:
        units_per = [place(p['input'], bg, prm) for p in train]
        if any(u is None or u == [] for u in units_per):
            continue
        for ray in (None, 2, 1):
            paints = [_paints(p['input'], bg, u, ray) for p, u in zip(train, units_per)]
            # colour options: 'same', or one colour per axis induced from outputs
            cmaps = [None]
            cm = {}; okc = True
            for p, pl in zip(train, paints):
                for (r, c), _, lab in pl:
                    if p['input'][r][c] == bg and p['output'][r][c] != bg:
                        if cm.setdefault(lab, p['output'][r][c]) != p['output'][r][c]:
                            okc = False
            if okc and cm: cmaps.append(cm)
            for cmap in cmaps:
                def fn(g, _place=place, _prm=prm, _ray=ray, _cm=cmap):
                    u = _place(g, bg, _prm)
                    if u is None: return [row[:] for row in g]
                    return _render(g, bg, u, _ray, _cm)
                if all(fn(p['input']) == p['output'] for p in train):
                    name = (f"optics:plane_mirror[place={kind}:{prm},ray={ray},"
                            f"colour={'same' if cmap is None else 'axis' + str(sorted(cmap.items()))},bg={bg}]")
                    yield (name, 3, fn)
                    return


FAMILIES = (fam_plane_mirror,)
