"""period_cell(x, y; axis, p): x contains a cell that a period-p continuation of object y would paint, i.e. a cell
outside y at offset exactly +p or -p along the axis from some cell of y (translation by one period of the frieze
generated by y).
  axis=row: along the row, same row, column offset +-p:     (r, c) -> (r, c +- p)
  axis=col: along the column, same column, row offset +-p:  (r, c) -> (r +- p, c)
Grounding: x is any individual (object or background cell), y an object, x != y; the painted cell must lie inside the
grid and outside y (cells y already occupies are not painted); x qualifies when it contains at least one such cell.
Positions only, colours are not compared.

Subsumption: none declared; period_cell[p] and period_cell[2p] are incomparable (offset exactly p, not a multiple)."""


def period_cell(grid, inds, bg, axis, p):
    d = ((0, p), (0, -p)) if axis == "row" else ((p, 0), (-p, 0))
    owner = {}
    for i, ind in enumerate(inds):
        for q in ind["pix"]: owner.setdefault(q, []).append(i)
    out = {}
    for j, ind in enumerate(inds):
        if ind["kind"] != "object": continue
        pj = ind["pix"]
        hit = set()
        for r, c in pj:
            for dr, dc in d:
                q = (r + dr, c + dc)
                if q not in pj: hit.update(owner.get(q, ()))
        hit.discard(j)
        for i in hit: out.setdefault(i, set()).add(j)
    return {i: out[i] for i in sorted(out)}


ITEM = {"name": "period_cell", "layer": 1, "iri": "qsr:period_cell", "kind": "role",
        "params": {"axis": ["row", "col"], "p": [2, 3, 4]}, "subsumes": [],
        "definition": "x has a cell outside object y at offset exactly +p or -p along the axis (row: same row, "
                      "column offset; col: same column, row offset) from a cell of y: the cell a period-p "
                      "continuation of y would paint; x != y.",
        "fn": period_cell}
