"""g12 -- reflection / symmetric completion.

Outside concept: PLANE MIRROR (optics, ray diagram).
    A plane mirror is placed in the scene.  Every non-background cell is an object point whose virtual
    image lies at the mirrored position; the output paints those images (optionally in a colour that
    depends on the mirror's orientation, like a coloured ray diagram, or on the object colour) and may
    also draw the dashed "normal" construction line joining a point to its image.

Everything is induced from the task's own training pairs, from these finite domains:
  mirror placement:
     'line'      an explicit full-length single-colour line in the input is the mirror
     'handle'    per object: the mirror lies just beyond the object's bounding-box edge on the side
                 opposite ('far') or on the side of ('near') its protruding handle cell(s);
                 gap g in {1,2,3} half-cells beyond that edge (g=2: one empty row between object and image)
     'grid_h' / 'grid_v' / 'grid_hv'   the grid's centre line(s) are the mirror(s) (two mirrors at right
                 angles = a kaleidoscope: the whole D2 orbit of every point is painted)
  image colour rule:  'same' | 'by_axis' (mirror orientation -> colour) | 'by_src' (object colour -> colour)
  dashed construction line period p in {0 (none), 1, 2, 3}; with two mirrors the line runs to the image
     across the NEARER mirror (no line for points equidistant from both).
Background = most frequent colour of the input.  Images are painted only onto background cells.
"""
from collections import Counter, deque

_PLACEMENTS = (('line', None, None),) + tuple(
    ('handle', side, gap) for side in ('far', 'near') for gap in (1, 2, 3)) + (
    ('grid_hv', None, None), ('grid_h', None, None), ('grid_v', None, None))
_COLOUR_RULES = ('same', 'by_axis', 'by_src')
_PERIODS = (0, 1, 2, 3)
_OPP = {'top': 'bottom', 'bottom': 'top', 'left': 'right', 'right': 'left'}


def _bg(g):
    return Counter(v for row in g for v in row).most_common(1)[0][0]


def _reflect(p, axis):
    orient, tp = axis
    r, c = p
    return (tp - r, c) if orient == 'h' else (r, tp - c)


def _orbit(p, axes):
    """images of p under the group generated by 1 or 2 perpendicular mirrors: [(key, pos)]"""
    if len(axes) == 1:
        return [(axes[0][0], _reflect(p, axes[0]))]
    a, b = axes
    pa, pb = _reflect(p, a), _reflect(p, b)
    return [(a[0], pa), (b[0], pb), ('hv', _reflect(pa, b))]


def _nearer_axis(p, axes):
    if len(axes) == 1:
        return axes[0]
    d = []
    for ax in axes:
        orient, tp = ax
        d.append(abs(2 * (p[0] if orient == 'h' else p[1]) - tp))
    if d[0] == d[1]:
        return None
    return axes[0] if d[0] < d[1] else axes[1]


def _components(g, bg):
    H, W = len(g), len(g[0])
    seen = [[False] * W for _ in range(H)]
    comps = []
    for r in range(H):
        for c in range(W):
            if seen[r][c] or g[r][c] == bg:
                continue
            q = deque([(r, c)]); seen[r][c] = True; cells = []
            while q:
                y, x = q.popleft(); cells.append((y, x))
                for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    ny, nx = y + dy, x + dx
                    if 0 <= ny < H and 0 <= nx < W and not seen[ny][nx] and g[ny][nx] != bg:
                        seen[ny][nx] = True; q.append((ny, nx))
            comps.append(cells)
    return comps


def _handle_axis(cells, side, gap):
    rs = [r for r, _ in cells]; cs = [c for _, c in cells]
    r0, r1, c0, c1 = min(rs), max(rs), min(cs), max(cs)
    if r1 - r0 < 1 or c1 - c0 < 1:
        return None
    cnt = {'top': sum(1 for r, _ in cells if r == r0), 'bottom': sum(1 for r, _ in cells if r == r1),
           'left': sum(1 for _, c in cells if c == c0), 'right': sum(1 for _, c in cells if c == c1)}
    srt = sorted(cnt.values())
    if srt[0] >= srt[1]:                      # the handle side must be the unique thinnest side
        return None
    hs = min(cnt, key=cnt.get)
    s = _OPP[hs] if side == 'far' else hs
    if s == 'top':
        return ('h', 2 * r0 - gap)
    if s == 'bottom':
        return ('h', 2 * r1 + gap)
    if s == 'left':
        return ('v', 2 * c0 - gap)
    return ('v', 2 * c1 + gap)


def _place(g, bg, placement):
    """-> list of (cells, axes) groups, or None when the placement is undefined for this grid"""
    kind, side, gap = placement
    H, W = len(g), len(g[0])
    if kind == 'line':
        axes = []
        for r in range(H):
            if g[r][0] != bg and all(v == g[r][0] for v in g[r]):
                axes.append(('h', 2 * r, r))
        for c in range(W):
            if g[0][c] != bg and all(g[r][c] == g[0][c] for r in range(H)):
                axes.append(('v', 2 * c, c))
        if len(axes) != 1:
            return None
        orient, tp, idx = axes[0]
        cells = [(r, c) for r in range(H) for c in range(W)
                 if g[r][c] != bg and (r if orient == 'h' else c) != idx]
        return [(cells, [(orient, tp)])] if cells else None
    if kind == 'handle':
        groups = []
        for cells in _components(g, bg):
            ax = _handle_axis(cells, side, gap)
            if ax is None:
                return None
            groups.append((cells, [ax]))
        return groups or None
    cells = [(r, c) for r in range(H) for c in range(W) if g[r][c] != bg]
    if not cells:
        return None
    axes = []
    if 'h' in kind[5:]:
        axes.append(('h', H - 1))
    if 'v' in kind[5:]:
        axes.append(('v', W - 1))
    return [(cells, axes)]


def _events(g, bg, groups):
    """[(src_colour, key, image_pos)] for images that land on background cells inside the grid"""
    H, W = len(g), len(g[0])
    ev = []
    for cells, axes in groups:
        for p in cells:
            src = g[p[0]][p[1]]
            for key, (rr, cc) in _orbit(p, axes):
                if 0 <= rr < H and 0 <= cc < W and g[rr][cc] == bg:
                    ev.append((src, key, (rr, cc)))
    return ev


def _make(placement, rule, cmap, period):
    def colour(src, key):
        if rule == 'same':
            return src
        return cmap.get(key if rule == 'by_axis' else src, src)

    def fn(g):
        bg = _bg(g)
        H, W = len(g), len(g[0])
        out = [row[:] for row in g]
        groups = _place(g, bg, placement)
        if groups is None:
            return out
        pts = []
        for cells, axes in groups:
            for p in cells:
                src = g[p[0]][p[1]]
                pts.append((p, src, axes))
                for key, (rr, cc) in _orbit(p, axes):
                    if 0 <= rr < H and 0 <= cc < W and g[rr][cc] == bg:
                        col = colour(src, key)
                        out[rr][cc] = col
                        pts.append(((rr, cc), col, axes))
        if period:
            for p, col, axes in pts:
                ax = _nearer_axis(p, axes)
                if ax is None:
                    continue
                q = _reflect(p, ax)
                dr, dc = q[0] - p[0], q[1] - p[1]
                n = max(abs(dr), abs(dc))
                if n == 0:
                    continue
                sr, sc = (dr > 0) - (dr < 0), (dc > 0) - (dc < 0)
                for k in range(0, n + 1, period):
                    rr, cc = p[0] + sr * k, p[1] + sc * k
                    if 0 <= rr < H and 0 <= cc < W and out[rr][cc] == bg:
                        out[rr][cc] = col
        return out
    return fn


def fam_plane_mirror(train):
    # quick global rejection: same-size outputs that preserve every input cell
    for p in train:
        a, b = p['input'], p['output']
        if len(a) != len(b) or len(a[0]) != len(b[0]):
            return
        bg = _bg(a)
        if any(a[r][c] != bg and b[r][c] != a[r][c] for r in range(len(a)) for c in range(len(a[0]))):
            return
    for placement in _PLACEMENTS:
        events = []
        ok = True
        for p in train:
            a, b = p['input'], p['output']
            bg = _bg(a)
            groups = _place(a, bg, placement)
            if groups is None:
                ok = False; break
            ev = _events(a, bg, groups)
            if not ev:
                ok = False; break
            for src, key, (rr, cc) in ev:
                obs = b[rr][cc]
                if obs == bg:          # the mechanism paints there but the output does not
                    ok = False; break
                events.append((src, key, obs))
            if not ok:
                break
        if not ok:
            continue
        rules = []
        if all(obs == src for src, _, obs in events):
            rules.append(('same', {}))
        for rule, ix in (('by_axis', 1), ('by_src', 0)):
            m = {}
            good = True
            for e in events:
                k = e[ix]
                if m.setdefault(k, e[2]) != e[2]:
                    good = False; break
            if good:
                rules.append((rule, m))
        for rule, cmap in rules:
            for period in _PERIODS:
                fn = _make(placement, rule, cmap, period)
                if all(fn(p['input']) == p['output'] for p in train):
                    kind, side, gap = placement
                    tag = kind if side is None else f'{kind}:{side}:g{gap}'
                    cm = '' if not cmap else ',' + '/'.join(f'{k}->{v}' for k, v in sorted(cmap.items(), key=str))
                    yield (f'optics:plane_mirror[{tag},{rule}{cm},dash={period}]', 3, fn)


FAMILIES = (fam_plane_mirror,)
