"""Prior family: mirror_symmetry_completion, priors4 (test-blind; Fable v11 T68 / D38 / G68 changed): every colour
parameter is a declared colour role (colour_roles: background, rank_colour(k), novel_colour) or a role-bound
participant colour (mirror colour, marker, the unit's own colours, participants' majority); no literal colours.

G68 BINDINGS (priors4) -- per member, the role each former literal became (training pairs only)
  2697da3f, 2b01abd0, 47c1f68c, 7ed72f31, 88207623, 93c31fbe, 9d9215db, bf32578f, db0c5428: no literal colour
            in the first fitting program (roles: own, swap2, mirror, shared, minority, marker, majority)
  2bcee788  new background 3 (priors3 induced literal)      <- novel_colour(train)
  6f473927  bg 0 = most frequent colour over the training inputs (priors3 constant 'tbg')
                                                           <- train_background (role-bound value defined here:
                                                              CR.background of the pooled training inputs)
            role table: background cell -> 8 (literal)     <- novel_colour(train);  object cell -> background (role)
  dc2e9a9d  axis table {v: 1, h: 8} (both new in every output) -> LOST: needs literal 1, 8 (novel_colour is not
            unique, no input role names them)
  846bdb03  not fitted before or after (move + crop)
  Literal slots removed (6): bg 'train' constant (-> train_background); glued mirror colour 'literal colour from
  training' (dropped; per-grid shared / per-object minority kept); new background induced literal (-> novel_colour
  | rank_colour(k) of the grid); role-table literal value, axis-table literal values, colour-table literal keys and
  values (keys -> the source colour's rank position on the grid; values -> background | source | novel_colour |
  rank_colour(k)).  Background is CR.background.

Earlier pass (priors3):

One generator.  A PLACEMENT finds the symmetry element(s) and splits the grid into units
(participants S, mirror cells M, generating isometries ms).  Every participant cell is sent through the
group generated by ms (bounded orbit); each image is written on background in an image colour; the
originals, the mirror cells and the strays are kept or recoloured/erased; optionally the completed figure
is replaced by its filled interior, leftover background takes a new colour, and mirror lines are cut out
of the canvas.  Every rule is a role (bg, mirror colour, marker colour, unit's own two colours) or a small
lookup table induced from the training pairs; there are no coordinates, sizes or colour numbers.

Isometries are written on doubled coordinates: ('v',k) c->k-c, ('h',k) r->k-r, ('t',d) main diagonal
r-c=d, ('a',s) anti-diagonal r+c=s, ('p',(kr,kc)) point mirror.

BINDINGS (G68) -- every value induced for the fitted members, with the role that explains it
(value seen in training  <-  role it is bound to; "literal" = no input role explains it, kept as a fitted constant).
  2697da3f  centre    <- 90-degree rotation centre of a square canvas of side 2w+h (w,h <- cropped shape's box)
            turns k=0 <- literal (the cropped shape is already the left arm)
  2b01abd0  mirror    <- the full-length uniform line;  originals' colour <- the unit's own other colour (swap2)
  2bcee788  mirror 2  <- the colour glued to every two-colour object = that object's MINORITY colour (per object);
            plane     <- just beyond the glued cells (edge);  mirror cells erased;  new bg 3 <- literal
            (the colour new in every output; absent from every input, so no input role can name it)
  47c1f68c  mirror    <- the full-length uniform cross;  image & original colour <- the mirror's colour;
            canvas    <- the input with the mirror lines cut out
  6f473927  bg        <- the colour common to all training inputs;  canvas doubled on the side away from the
            heavier border;  image colour <- the source cell's ROLE: object cell -> background, background
            cell -> 8 (literal, the colour new in every output)  [old: literal table {2:0, 0:8}]
  7ed72f31  mirror 2  <- the colour shared by every multi-colour object of the grid (per grid);  plane/point
            <- the mirror cells' own line or cell (on)
  88207623  mirror 2  <- each object's minority colour (the per-grid shared colour is not unique in its pairs);
            image colour <- the marker (the foreign cell lying inside the unit's image)
  93c31fbe  mirrors   <- the centre lines of the bracket frame;  strays erased
  9d9215db  group     <- the grid's two midlines;  dotted-ray step 2 <- the participants' lattice pitch
            (gcd of their row/col offsets)  [old: literal 2]
  bf32578f  mirror    <- the grid's vertical midline;  render interior, fill <- the participants' majority colour
  dc2e9a9d  plane     <- beside the object's flat side;  gap 1 <- the depth of the object's bump on the opposite
            side  [old: literal 1];  image colour <- axis table {v:1, h:8} (literal: both colours new in outputs)
Specialisation menu built from the table (role-bound alternatives tried before the literal ones):
  glued mirror colour in {per-grid shared colour, per-object minority colour, literal colour from training}
  object gap          in {bump depth, literal 1, 0, 2}
  ray step            in {lattice pitch, literal 2, 1}
  image colour        adds 'role' (table keyed by the source cell's role bg/object, valued bg | source | literal)
  plane side          in {flat, bump, E/W/S/N literal, the unit's own OUTWARD/INWARD side} -- the last one is
                      the widening: a figure tiled 3x3 round an empty centre tile (an annulus) has border tiles
                      whose mirror is the box edge they lie on (gap 0, the object placement's own-edge plane):
                      outward across the figure's box (a corner tile through the corner = both sides composed)
                      and inward across the hole's box, each hole cell owned by the tile in its radial
                      direction; the directionless hole centre takes the participants' majority colour (the
                      same fill role as render=interior).  Fits db0c5428.
Not widened: 846bdb03 (the loose shape is TRANSLATED into a corner-marked frame, flipped only when its colours
  face the wrong bars, and the canvas is cropped to the frame -- move+crop, no mirror-completion step shared).
"""
from collections import Counter
from itertools import islice
from math import gcd

import colour_roles as CR

CARD = "prior4_mirror_symmetry_completion"
CONCEPT = "mirror_symmetry_completion"
MEMBERS = ["2697da3f", "2b01abd0", "2bcee788", "47c1f68c", "6f473927", "7ed72f31", "846bdb03",
           "88207623", "93c31fbe", "9d9215db", "bf32578f", "db0c5428", "dc2e9a9d"]
READING = {
    "generator": ("REFLECT: find the symmetry element (full-length axis line(s), the grid midlines, a mirror "
                  "colour glued to each shape acting as point/plane mirror on or just beyond it, a plane beside "
                  "each asymmetric object, the centre lines of a bracket frame, the grid border with the "
                  "canvas doubled, a 90-degree rotation centre round which the cropped shape is an arm, or the box "
                  "edges each border tile of a 3x3-tiled annulus lies on) and write every participant's image under the generated group on background, "
                  "recolouring images/originals by role, erasing mirror or strays as induced."),
    "stop": "bounded orbit (<=16 points) of each participant; images only on background cells, first writer wins",
    "params": ("bg in {grid, train background} . placement in {line, grid:V|H|VH|D4, glued:(mirror colour <- "
               "per-grid shared | per-object minority, on|edge, conn 8|4), object:(flat|bump|E|W|S|N, gap <- bump depth | 0|1|2), "
               "unfold:(both|out; side <- each border tile's own outward/inward side), frame:(both|one), border:(cols|rows), "
               "rot4:(quarter turns 0..3)} . ray in {none, lattice pitch, 2, 1} (grid only) . image colour in {keep, swap2, "
               "mirror, marker, role-table (bg/object -> role), axis-table (axis -> role), colour-table (rank position "
               "-> role); role in {bg, source, novel, rank k}} . "
               "original colour in {keep, swap2, mirror} . mirror cells in {keep, erase} . strays in {keep, erase} . "
               "render in {figure, interior} . new background in {none, novel, rank k} . canvas in {same, cut lines, doubled, square of side 2w+h}"),
    "participants": ("background = most frequent colour; mirror = uniform full rows/cols, the colour shared by all "
                     "multi-colour objects, L-tromino bracket corners, or grid midlines/border; participants = the "
                     "other cells of the unit; marker = a foreign cell inside a unit's image"),
    "preconditions": ("output is the same size as the input, the input with its axis lines cut out, the input "
                      "doubled along one axis, or a larger square; the induced colour rules are consistent over all training pairs"),
}


# ------------------------------------------------------------------ helpers
def _bgc(g):
    return CR.background(g)


def _train_bg(train):
    """role-bound value: the background of the training set = CR.background of all training input cells pooled"""
    return CR.background([row for p in train for row in p['input']])


def _roles(G, bg, cache):
    """declared roles on grid G: values {('rank',k): colour} and rank positions {colour: k} (memoised in cache)"""
    r = cache.get('_roles')
    if r is None:
        tal = Counter(v for row in G for v in row if v != bg)
        order = sorted(tal, key=lambda x: (-tal[x], x))
        r = cache['_roles'] = ({('rank', k): CR.rank_colour(G, k, bg) for k in CR.RANKS},
                               {v: i + 1 for i, v in enumerate(order)})
    return r


def _rname(spec):
    return 'none' if spec is None else ('novel' if spec[0] == 'novel' else 'rank%d' % spec[1])


def _rv(spec, G, bg, v, cache):
    """a role value: 'bg', 'src' (the source cell's colour), ('novel', c) fixed by training, ('rank', k) on G"""
    if spec == 'bg':
        return bg
    if spec == 'src':
        return v
    if spec[0] == 'novel':
        return spec[1]
    return _roles(G, bg, cache)[0].get(spec)


_CC = {}


def _comps(g, bg, conn=8):
    """memoised on grid content (callers never mutate the returned cell lists)"""
    key = (tuple(map(tuple, g)), bg, conn)
    res = _CC.get(key)
    if res is None:
        if len(_CC) > 256:
            _CC.clear()
        res = _CC[key] = _comps_raw(g, bg, conn)
    return res


def _comps_raw(g, bg, conn):
    H, W = len(g), len(g[0])
    if conn == 8:
        nb = [(a, b) for a in (-1, 0, 1) for b in (-1, 0, 1) if a or b]
    else:
        nb = [(1, 0), (-1, 0), (0, 1), (0, -1)]
    seen = set()
    out = []
    for r in range(H):
        for c in range(W):
            if g[r][c] == bg or (r, c) in seen:
                continue
            seen.add((r, c))
            st, cells = [(r, c)], []
            while st:
                y, x = st.pop()
                cells.append((y, x))
                for dy, dx in nb:
                    q = (y + dy, x + dx)
                    if 0 <= q[0] < H and 0 <= q[1] < W and q not in seen and g[q[0]][q[1]] != bg:
                        seen.add(q)
                        st.append(q)
            out.append(cells)
    return out


def _mono_comps(g, col):
    H, W = len(g), len(g[0])
    seen, out = set(), []
    for r in range(H):
        for c in range(W):
            if g[r][c] != col or (r, c) in seen:
                continue
            seen.add((r, c))
            st, cells = [(r, c)], []
            while st:
                y, x = st.pop()
                cells.append((y, x))
                for q in ((y + 1, x), (y - 1, x), (y, x + 1), (y, x - 1)):
                    if 0 <= q[0] < H and 0 <= q[1] < W and q not in seen and g[q[0]][q[1]] == col:
                        seen.add(q)
                        st.append(q)
            out.append(cells)
    return out


def _refl(p, m):
    ax, k = m
    r, c = p
    if ax == 'v':
        return (r, k - c)
    if ax == 'h':
        return (k - r, c)
    if ax == 't':
        return (c + k, r - k)
    if ax == 'a':
        return (k - c, k - r)
    if ax == 'r':                       # quarter turn clockwise about the doubled centre k
        return ((k[0] + 2 * c - k[1]) // 2, (k[1] - 2 * r + k[0]) // 2)
    return (k[0] - r, k[1] - c)


def _rfn(m):
    ax, k = m
    if ax == 'v':
        return lambda r, c: (r, k - c)
    if ax == 'h':
        return lambda r, c: (k - r, c)
    if ax == 't':
        return lambda r, c: (c + k, r - k)
    if ax == 'a':
        return lambda r, c: (k - c, k - r)
    if ax == 'r':
        return lambda r, c: ((k[0] + 2 * c - k[1]) // 2, (k[1] - 2 * r + k[0]) // 2)
    return lambda r, c: (k[0] - r, k[1] - c)


def _orbit(p, ms, H, W):
    if len(ms) == 1 and ms[0][0] != 'r':          # an involution: the orbit is p and its one image
        q2 = _refl(p, ms[0])
        if q2 != p and -H <= q2[0] < 2 * H and -W <= q2[1] < 2 * W:
            return {p: None, q2: ms[0][0]}
        return {p: None}
    orb = {p: None}
    st = [p]
    while st and len(orb) < 16:
        q = st.pop()
        for m in ms:
            q2 = _refl(q, m)
            if q2 not in orb and -H <= q2[0] < 2 * H and -W <= q2[1] < 2 * W:
                orb[q2] = orb[q] or m[0]
                st.append(q2)
    return orb


def _is_sym(cells, g, m):
    s = set(cells)
    for p in cells:
        q = _refl(p, m)
        if q not in s or g[p[0]][p[1]] != g[q[0]][q[1]]:
            return False
    return True


def _unit(S, M, ms, mc=None):
    return {'S': S, 'M': M, 'ms': ms, 'mc': mc}


# ------------------------------------------------------------------ placements: g, bg, prm -> (G, units, drop_rows, drop_cols)
def _pl_line(g, bg, prm):
    H, W = len(g), len(g[0])
    rows = [r for r in range(H) if g[r][0] != bg and len(set(g[r])) == 1]
    cols = [c for c in range(W) if g[0][c] != bg and len({g[r][c] for r in range(H)}) == 1]
    if not rows and not cols or len(rows) + len(cols) > 2:
        return None
    ms = [('h', 2 * r) for r in rows] + [('v', 2 * c) for c in cols]
    rs, cs = set(rows), set(cols)
    M = [(r, c) for r in range(H) for c in range(W) if r in rs or c in cs]
    S = [(r, c) for r in range(H) for c in range(W) if g[r][c] != bg and r not in rs and c not in cs]
    mc = g[rows[0]][0] if rows else g[0][cols[0]]
    cut = prm == 'cut'
    return g, [_unit(S, M, ms, mc)], (rs if cut else set()), (cs if cut else set())


def _pl_grid(g, bg, group):
    H, W = len(g), len(g[0])
    if group == 'D4' and H != W:
        return None
    ms = {'V': [('v', W - 1)], 'H': [('h', H - 1)], 'VH': [('v', W - 1), ('h', H - 1)],
          'D4': [('v', W - 1), ('h', H - 1), ('t', 0)]}[group]
    S = [(r, c) for r in range(H) for c in range(W) if g[r][c] != bg]
    if not S:
        return None
    return g, [_unit(S, [], ms)], set(), set()


def _flat_reflector(M):
    if len(M) == 1:
        (y, x), = M
        return ('p', (2 * y, 2 * x))
    ys, xs = {y for y, _ in M}, {x for _, x in M}
    if len(ys) == 1:
        return ('h', 2 * next(iter(ys)))
    if len(xs) == 1:
        return ('v', 2 * next(iter(xs)))
    d = {y - x for y, x in M}
    if len(d) == 1:
        return ('t', next(iter(d)))
    s = {y + x for y, x in M}
    if len(s) == 1:
        return ('a', next(iter(s)))
    return None


def _edge_reflector(M, S):
    sset = set(S)
    for mode in (all, any):
        for dr, dc in ((0, 1), (0, -1), (1, 0), (-1, 0)):
            if mode((r + dr, c + dc) in sset for r, c in M):
                if dr:
                    ys = {y for y, _ in M}
                    return ('h', 2 * next(iter(ys)) + dr) if len(ys) == 1 else None
                xs = {x for _, x in M}
                return ('v', 2 * next(iter(xs)) + dc) if len(xs) == 1 else None
    return None


def _shared_colour(g, bg, conn):
    """role: the one colour shared by every multi-colour object of this grid (None when not unique)"""
    shared = None
    for comp in _comps(g, bg, conn):
        cols = {g[y][x] for y, x in comp}
        if len(cols) >= 2:
            shared = cols if shared is None else shared & cols
    return next(iter(shared)) if shared and len(shared) == 1 else None


def _minority(g, comp):
    """role: the object's own least frequent colour (None on a tie or a one-colour object)"""
    cnt = Counter(g[y][x] for y, x in comp).most_common()
    if len(cnt) < 2 or cnt[-1][1] == cnt[-2][1]:
        return None
    return cnt[-1][0]


def _pl_glued(g, bg, prm):
    mcb, pos, conn = prm
    mc = _shared_colour(g, bg, conn) if mcb == 'shared' else mcb
    if mc is None:
        return None
    units = []
    for comp in _comps(g, bg, conn):
        if mcb == 'minority':
            mc = _minority(g, comp)
            if mc is None:
                continue
        M = [p for p in comp if g[p[0]][p[1]] == mc]
        S = [p for p in comp if g[p[0]][p[1]] != mc]
        if not M or not S:
            continue
        m = _flat_reflector(M) if pos == 'on' else _edge_reflector(M, S)
        if m is None:
            continue
        units.append(_unit(S, M, [m], mc))
    if not units:
        return None
    return g, units, set(), set()


def _bump_depth(counts, from_lo):
    """role: how many lines, from the light side, hold fewer cells than the fullest line (the bump's depth)"""
    seq = counts if from_lo else counts[::-1]
    full = max(counts)
    d = 0
    for n in seq:
        if n >= full:
            break
        d += 1
    return d


def _pl_object(g, bg, prm):
    side, gap0 = prm
    units = []
    for cells in _comps(g, bg, 8):
        rs = [p[0] for p in cells]
        cs = [p[1] for p in cells]
        r0, r1, c0, c1 = min(rs), max(rs), min(cs), max(cs)
        gap = gap0
        if gap0 == 'bump' and side in ('flat', 'bump'):
            symv = _is_sym(cells, g, ('v', c0 + c1))
            if not symv:
                cnt = [cs.count(c) for c in range(c0, c1 + 1)]
                lo_light = cs.count(c0) < cs.count(c1)
            else:
                cnt = [rs.count(r) for r in range(r0, r1 + 1)]
                lo_light = rs.count(r0) < rs.count(r1)
            gap = _bump_depth(cnt, lo_light)
        if side in ('E', 'W', 'S', 'N'):
            m = {'E': ('v', 2 * c1 + 1 + gap), 'W': ('v', 2 * c0 - 1 - gap),
                 'S': ('h', 2 * r1 + 1 + gap), 'N': ('h', 2 * r0 - 1 - gap)}[side]
        else:
            symv = _is_sym(cells, g, ('v', c0 + c1))
            symh = _is_sym(cells, g, ('h', r0 + r1))
            if symv == symh:
                continue
            if not symv:
                n_lo, n_hi = cs.count(c0), cs.count(c1)
                if n_lo == n_hi:
                    continue
                hi = (n_hi > n_lo) == (side == 'flat')
                m = ('v', 2 * c1 + 1 + gap) if hi else ('v', 2 * c0 - 1 - gap)
            else:
                n_lo, n_hi = rs.count(r0), rs.count(r1)
                if n_lo == n_hi:
                    continue
                hi = (n_hi > n_lo) == (side == 'flat')
                m = ('h', 2 * r1 + 1 + gap) if hi else ('h', 2 * r0 - 1 - gap)
        units.append(_unit(cells, [], [m]))
    if not units:
        return None
    return g, units, set(), set()


def _bracket(cells):
    if len(cells) != 3:
        return None
    r0 = min(a for a, _ in cells)
    c0 = min(b for _, b in cells)
    s = {(a - r0, b - c0) for a, b in cells}
    box = {(0, 0), (0, 1), (1, 0), (1, 1)}
    if not s <= box:
        return None
    return {(1, 1): 'TL', (1, 0): 'TR', (0, 1): 'BL', (0, 0): 'BR'}[(box - s).pop()], r0, c0


def _pl_frame(g, bg, mode):
    H, W = len(g), len(g[0])
    frames = []
    fcols = set()
    for col in sorted({v for row in g for v in row} - {bg}):
        cs = _mono_comps(g, col)
        if len(cs) < 4:
            continue
        br = [_bracket(x) for x in cs]
        if not all(br):
            continue
        fcols.add(col)
        corner = {}
        for k, r0, c0 in br:
            corner.setdefault(k, []).append((r0, c0))
        for (r, q) in corner.get('TL', []):
            trs = sorted(x for x in corner.get('TR', []) if x[0] == r and x[1] > q)
            bls = sorted(x for x in corner.get('BL', []) if x[1] == q and x[0] > r)
            if trs and bls:
                frames.append((col, r, bls[0][0] + 1, q, trs[0][1] + 1))
    if not frames:
        return None
    units = []
    for col, r0, r1, c0, c1 in frames:
        M = [(i, j) for i in range(r0, r1 + 1) for j in range(c0, c1 + 1) if g[i][j] == col]
        ir0, ir1, ic0, ic1 = r0 + 1, r1 - 1, c0 + 1, c1 - 1
        S = [(i, j) for i in range(ir0, ir1 + 1) for j in range(ic0, ic1 + 1)
             if g[i][j] != bg and g[i][j] not in fcols]
        sr, sc = ir0 + ir1, ic0 + ic1
        ms = []
        if S:
            vert = all(2 * i < sr for i, _ in S) or all(2 * i > sr for i, _ in S)
            horz = all(2 * j < sc for _, j in S) or all(2 * j > sc for _, j in S)
            if mode == 'one' and vert and horz:
                horz = False
            if horz:
                ms.append(('v', sc))
            if vert:
                ms.append(('h', sr))
        units.append(_unit(S, M, ms, col))
    return g, units, set(), set()


def _pl_border(g, bg, orient):
    H, W = len(g), len(g[0])
    if orient == 'cols':
        lo = sum(1 for r in g if r[0] != bg)
        hi = sum(1 for r in g if r[-1] != bg)
        if lo > hi:
            G = [[bg] * W + list(r) for r in g]
            S = [(r, c + W) for r in range(H) for c in range(W)]
        else:
            G = [list(r) + [bg] * W for r in g]
            S = [(r, c) for r in range(H) for c in range(W)]
        ms = [('v', 2 * W - 1)]
    else:
        lo = sum(1 for v in g[0] if v != bg)
        hi = sum(1 for v in g[-1] if v != bg)
        if lo > hi:
            G = [[bg] * W for _ in range(H)] + [list(r) for r in g]
            S = [(r + H, c) for r in range(H) for c in range(W)]
        else:
            G = [list(r) for r in g] + [[bg] * W for _ in range(H)]
            S = [(r, c) for r in range(H) for c in range(W)]
        ms = [('h', 2 * H - 1)]
    return G, [_unit(S, [], ms)], set(), set()


def _rot_cw(m):
    h = len(m)
    return [[m[h - 1 - c][r] for c in range(h)] for r in range(len(m[0]))]


def _pl_rot4(g, bg, k):
    """90-degree rotation centre: the cropped shape (turned k quarter turns) becomes the left arm of a square
    canvas whose four arms (the C4 images) meet round a central hole as tall as the arm."""
    cells = [(r, c) for r, row in enumerate(g) for c, v in enumerate(row) if v != bg]
    if not cells:
        return None
    r0, r1 = min(r for r, _ in cells), max(r for r, _ in cells)
    c0, c1 = min(c for _, c in cells), max(c for _, c in cells)
    s = [row[c0:c1 + 1] for row in g[r0:r1 + 1]]
    for _ in range(k):
        s = _rot_cw(s)
    h, w = len(s), len(s[0])
    N = 2 * w + h
    if N > 30:
        return None
    G = [[bg] * N for _ in range(N)]
    S = []
    for r in range(h):
        for c in range(w):
            if s[r][c] != bg:
                G[w + r][c] = s[r][c]
                S.append((w + r, c))
    return G, [_unit(S, [], [('r', (N - 1, N - 1))])], set(), set()


def _annulus(g, bg):
    """the figure (all non-bg cells) is a 3x3 arrangement of th x tw tiles whose centre tile is the only hole"""
    cells = [(r, c) for r, row in enumerate(g) for c, v in enumerate(row) if v != bg]
    if not cells:
        return None
    r0, r1 = min(r for r, _ in cells), max(r for r, _ in cells)
    c0, c1 = min(c for _, c in cells), max(c for _, c in cells)
    h, w = r1 - r0 + 1, c1 - c0 + 1
    if h % 3 or w % 3 or len(cells) != h * w * 8 // 9:
        return None
    th, tw = h // 3, w // 3
    for r in range(r0, r1 + 1):
        for c in range(c0, c1 + 1):
            inner = r0 + th <= r < r0 + 2 * th and c0 + tw <= c < c0 + 2 * tw
            if (g[r][c] == bg) != inner:
                return None
    return r0, c0, th, tw, cells


def _sgn(x):
    return (x > 0) - (x < 0)


def _pl_unfold(g, bg, mode):
    """each border tile is a flap whose mirror is the box edge(s) it lies on (its own outer side, gap 0):
    outward across the figure's box, and (mode 'both') inward across the hole's box with every hole cell owned by
    the tile in its radial direction; the directionless hole centre takes the participants' majority colour."""
    a = _annulus(g, bg)
    if a is None:
        return None
    r0, c0, th, tw, cells = a
    R0, R1, C0, C1 = 2 * r0 - 1, 2 * (r0 + 3 * th) - 1, 2 * c0 - 1, 2 * (c0 + 3 * tw) - 1     # figure box edges
    h0, h1, k0, k1 = 2 * (r0 + th) - 1, 2 * (r0 + 2 * th) - 1, 2 * c0 + 2 * tw - 1, 2 * (c0 + 2 * tw) - 1  # hole
    sector = {}
    fill = []
    if mode == 'both':
        for i in range(th):
            for j in range(tw):
                di, dj = (2 * i - (th - 1)) * tw, (2 * j - (tw - 1)) * th
                q = (r0 + th + i, c0 + tw + j)
                if di == 0 and dj == 0:
                    fill.append(q)
                    continue
                d = (_sgn(di) if abs(di) >= abs(dj) else 0, _sgn(dj) if abs(dj) >= abs(di) else 0)
                sector.setdefault(d, set()).add(q)
    units = []
    for dr in (-1, 0, 1):
        for dc in (-1, 0, 1):
            if not dr and not dc:
                continue
            S = [(r0 + (1 + dr) * th + i, c0 + (1 + dc) * tw + j) for i in range(th) for j in range(tw)]
            sides = [((R0, R1)[dr > 0], (C0, C1)[dc > 0], None)]                 # outward: the figure's box
            if sector.get((dr, dc)):
                sides.append(((h0, h1)[dr > 0], (k0, k1)[dc > 0], sector[(dr, dc)]))   # inward: the hole's box
            for kr, kc, allow in sides:
                if dr and dc:
                    m = ('p', (kr, kc))                   # corner tile: both of its sides composed
                elif dr:
                    m = ('h', kr)
                else:
                    m = ('v', kc)
                u = _unit(S, [], [m])
                if allow is not None:
                    u['allow'] = allow
                units.append(u)
    if fill:
        body = Counter(g[r][c] for r, c in cells).most_common(1)[0][0]
        u = _unit([], [], [])
        u['fill'] = [(q, body) for q in fill]
        units.append(u)
    return g, units, set(), set()


PLACEMENTS = ([('line', _pl_line, 'keep'), ('line', _pl_line, 'cut')]
              + [('grid', _pl_grid, gr) for gr in ('V', 'H', 'VH', 'D4')]
              + [('object', _pl_object, (sd, gp)) for sd in ('flat', 'bump') for gp in ('bump', 1, 0, 2)]
              + [('object', _pl_object, (sd, gp)) for sd in ('E', 'W', 'S', 'N') for gp in (0, 1)]
              + [('unfold', _pl_unfold, md) for md in ('both', 'out')]
              + [('frame', _pl_frame, md) for md in ('both', 'one')]
              + [('border', _pl_border, o) for o in ('cols', 'rows')]
              + [('rot4', _pl_rot4, k) for k in range(4)])


# ------------------------------------------------------------------ image formation
def _paints(G, units, ray):
    """list of (unit index, (r,c), source colour, axis label): images, then optional dotted rays"""
    out = _images(G, units)
    if ray:
        out += _rays(G, units, ray)
    return out


def _images(G, units):
    H, W = len(G), len(G[0])
    out = []
    app = out.append
    for ui, u in enumerate(units):
        for q, col in u.get('fill', ()):          # cells no participant owns: the participants' majority colour
            app((ui, q, col, 'c'))
        ms = u['ms']
        if not ms:
            continue
        allow = u.get('allow')
        if len(ms) == 1 and ms[0][0] != 'r':      # single involution: one image per point
            f, lab = _rfn(ms[0]), ms[0][0]
            for p in u['S']:
                r, c = p
                q = f(r, c)
                if q != p and 0 <= q[0] < H and 0 <= q[1] < W and (allow is None or q in allow):
                    app((ui, q, G[r][c], lab))
            continue
        for p in u['S']:
            v = G[p[0]][p[1]]
            for q, lab in _orbit(p, ms, H, W).items():
                if lab and 0 <= q[0] < H and 0 <= q[1] < W and (allow is None or q in allow):
                    app((ui, q, v, lab))
    return out


def _rays(G, units, ray):
    H, W = len(G), len(G[0])
    out = []
    if ray:
        for ui, u in enumerate(units):
            ax = [m for m in u['ms'] if m[0] in 'vh']
            if not ax or not u['S']:
                continue
            step0 = ray
            if ray == 'pitch':                    # role: the participants' lattice pitch
                y0, x0 = u['S'][0]
                step0 = 0
                for y, x in u['S']:
                    step0 = gcd(gcd(step0, y - y0), x - x0)
                if step0 < 1:
                    continue
            for p in u['S']:
                col = G[p[0]][p[1]]
                for q in _orbit(p, u['ms'], H, W):
                    d = sorted((abs(2 * (q[1] if m[0] == 'v' else q[0]) - m[1]), m) for m in ax)
                    if len(d) > 1 and d[0][0] == d[1][0]:
                        continue
                    dist, m = d[0]
                    if dist == 0:
                        continue
                    q2 = _refl(q, m)
                    i = 1 if m[0] == 'v' else 0
                    step = step0 if q2[i] > q[i] else -step0
                    x = list(q)
                    while (x[i] - q2[i]) * step < 0:
                        x[i] += step
                        if 0 <= x[0] < H and 0 <= x[1] < W:
                            out.append((ui, tuple(x), col, m[0]))
    return out


def _swap2(u, G):
    sw = u.get('_sw')
    if sw is None:
        cols = sorted({G[r][c] for r, c in u['S']})
        sw = u['_sw'] = {cols[0]: cols[1], cols[1]: cols[0]} if len(cols) == 2 else {}
    return sw


def _marker(u, G, bg, H, W):
    own = set(u['S']) | set(u['M'])
    if not any(v != bg and (r, c) not in own for r, row in enumerate(G) for c, v in enumerate(row)):
        return None                                   # no foreign cell anywhere
    for p in sorted(u['S']):
        for q in _orbit(p, u['ms'], H, W):
            if 0 <= q[0] < H and 0 <= q[1] < W and q not in own and G[q[0]][q[1]] != bg:
                return G[q[0]][q[1]]
    return None


def _img_colour(rule, table, u, G, bg, v, lab, cache):
    if rule == 'keep':
        return v
    if rule == 'swap2':
        return _swap2(u, G).get(v, v)
    if rule == 'mirror':
        return u['mc']
    if rule == 'marker':
        key = id(u)
        if key not in cache:
            cache[key] = _marker(u, G, bg, len(G), len(G[0]))
        return cache[key]
    if rule == 'axis':
        t = table.get(lab)
    elif rule == 'role':                          # keyed by the source cell's role (bg / object), valued by role
        t = table.get('bg' if v == bg else 'fg')
    else:                                         # keyed by the source colour's rank position on the grid
        t = table.get('bg' if v == bg else _roles(G, bg, cache)[1].get(v))
    return None if t is None else _rv(t, G, bg, v, cache)


def _orig_colour(rule, u, G, v):
    if rule == 'keep':
        return v
    if rule == 'swap2':
        return _swap2(u, G).get(v, v)
    return u['mc']


def _enclosed(F, H, W):
    if not F:
        return set()
    r0 = min(a for a, _ in F) - 1
    r1 = max(a for a, _ in F) + 1
    c0 = min(b for _, b in F) - 1
    c1 = max(b for _, b in F) + 1
    seen = {(r0, c0)}
    st = [(r0, c0)]
    while st:
        a, b = st.pop()
        for x, y in ((a + 1, b), (a - 1, b), (a, b + 1), (a, b - 1)):
            if r0 <= x <= r1 and c0 <= y <= c1 and (x, y) not in seen and (x, y) not in F:
                seen.add((x, y))
                st.append((x, y))
    return {(a, b) for a in range(r0, r1 + 1) for b in range(c0, c1 + 1)
            if (a, b) not in seen and (a, b) not in F and 0 <= a < H and 0 <= b < W}


def _render(G, bg, units, paints, P):
    """P: dict of rule choices. Returns same-size-as-G grid."""
    H, W = len(G), len(G[0])
    o = [row[:] for row in G]
    inS, inM = set(), set()
    for u in units:
        inS.update(u['S'])
        inM.update(u['M'])
    if P['strays'] == 'erase':
        for r in range(H):
            for c in range(W):
                if o[r][c] != bg and (r, c) not in inS and (r, c) not in inM:
                    o[r][c] = bg
    if P['mirror'] == 'erase':
        for r, c in inM:
            if (r, c) not in inS:
                o[r][c] = bg
    for u in units:
        for r, c in u['S']:
            o[r][c] = _orig_colour(P['orig'], u, G, G[r][c])
    cache = {}
    done = set()
    figure = set(inS)
    for ui, (r, c), v, lab in paints:
        if (r, c) in done or o[r][c] != bg:
            continue
        col = _img_colour(P['img'], P['table'], units[ui], G, bg, v, lab, cache)
        if col is None:
            continue
        o[r][c] = col
        done.add((r, c))
        figure.add((r, c))
    if P['render'] == 'interior':
        fcol = Counter(G[r][c] for r, c in inS).most_common(1)[0][0] if inS else bg
        o = [[bg] * W for _ in range(H)]
        for r, c in _enclosed(figure, H, W):
            o[r][c] = fcol
    if P['newbg'] is not None:
        nb = _rv(P['newbg'], G, bg, None, {})
        if nb is not None:
            o = [[nb if v == bg else v for v in row] for row in o]
    return o


def _cut(o, dr, dc):
    return [[v for c, v in enumerate(row) if c not in dc] for r, row in enumerate(o) if r not in dr]


# ------------------------------------------------------------------ induction
IMG_RULES = ('keep', 'swap2', 'mirror', 'marker', 'role', 'axis', 'map')
ORIG_RULES = ('keep', 'swap2', 'mirror')


def _maps(dr, dc, H, W):
    rm, k = {}, 0
    for r in range(H):
        if r not in dr:
            rm[r] = k
            k += 1
    cm, k = {}, 0
    for c in range(W):
        if c not in dc:
            cm[c] = k
            k += 1
    return rm, cm


def _induce_img(cases, decl=()):
    """cases: list of (G, bg, units, paints, out, rm, cm). Yields (rule, table) consistent at painted bg cells.
    Table values are roles: 'bg', 'src', then the declared roles decl (novel, rank k)."""
    order = ['bg', 'src'] + list(decl)
    for rule in IMG_RULES:
        table = {}
        ok = True
        any_paint = False
        for G, bg, units, paints, out, rm, cm in cases:
            cache, done = {}, set()
            for ui, (r, c), v, lab in paints:
                if (r, c) in done or G[r][c] != bg or r not in rm or c not in cm:
                    continue
                done.add((r, c))
                want = out[rm[r]][cm[c]]
                if rule in ('role', 'axis', 'map'):
                    cand = {x for x in order if _rv(x, G, bg, v, cache) == want}
                    if rule == 'role':
                        key = 'bg' if v == bg else 'fg'
                    elif rule == 'axis':
                        key = lab
                    else:
                        key = 'bg' if v == bg else _roles(G, bg, cache)[1].get(v)
                    cur = table[key] = table[key] & cand if key in table else cand
                    if not cur:
                        ok = False
                        break
                    any_paint = True
                else:
                    got = _img_colour(rule, table, units[ui], G, bg, v, lab, cache)
                    if got is None:
                        continue
                    any_paint = True
                    if got != want:
                        ok = False
                        break
            if not ok:
                break
        if ok and any_paint and rule in ('role', 'axis', 'map'):
            # the first role (in order) explaining every observation; 'role' only earns its place when it is not
            # plain 'keep'
            table = {k: next(x for x in order if x in s) for k, s in table.items()}
            if rule == 'role' and all(x == 'src' for x in table.values()):
                continue
        if ok and any_paint:
            yield rule, table


def _induce_orig(cases):
    res = []
    for rule in ORIG_RULES:
        ok = True
        for G, bg, units, paints, out, rm, cm in cases:
            for u in units:
                for r, c in u['S']:
                    if r in rm and c in cm and out[rm[r]][cm[c]] != _orig_colour(rule, u, G, G[r][c]):
                        ok = False
                        break
                if not ok:
                    break
            if not ok:
                break
        if ok:
            res.append(rule)
    return res


def _induce_keep(cases, which):
    """'keep' if the output keeps the input colour on every mirror (or stray) cell, else 'erase'."""
    for G, bg, units, paints, out, rm, cm in cases:
        inS, inM = set(), set()
        for u in units:
            inS.update(u['S'])
            inM.update(u['M'])
        H, W = len(G), len(G[0])
        if which == 'mirror':
            cells = inM - inS
        else:
            cells = {(r, c) for r in range(H) for c in range(W)
                     if G[r][c] != bg and (r, c) not in inS and (r, c) not in inM}
        for r, c in cells:
            if r in rm and c in cm and out[rm[r]][cm[c]] != G[r][c]:
                return 'erase'
    return 'keep'


def _interior_possible(G, bg, units, out, newbg):
    """necessary condition for render=interior: the output holds only (mapped) background and figure colour"""
    inS = set()
    for u in units:
        inS.update(u['S'])
    fcol = Counter(G[r][c] for r, c in inS).most_common(1)[0][0] if inS else bg
    if newbg is not None:
        newbg = _rv(newbg, G, bg, None, {})
    allowed = {(newbg if (newbg is not None and x == bg) else x) for x in (bg, fcol)}
    return all(v in allowed for row in out for v in row)


def _fits(cases, res_per, P):
    """same as fn(input) == output for every training pair, reusing the placements and paints already built"""
    for (G, bg, units, paints, out, _, _), (_, (_, _, dr, dc)) in zip(cases, res_per):
        o = _render(G, bg, units, paints, P)
        if dr or dc:
            o = _cut(o, dr, dc)
        if o != out:
            return False
    return True


def _make(bgmode, tbg, place, prm, ray, P):
    def fn(g):
        bg = tbg if bgmode == 'train' else _bgc(g)
        res = place(g, bg, prm)
        if res is None:
            return [row[:] for row in g]
        G, units, dr, dc = res
        o = _render(G, bg, units, _paints(G, units, ray), P)
        return _cut(o, dr, dc) if (dr or dc) else o
    return fn


def fam(train):
    if not train:
        return
    # fast precondition: same size, one or two lines shorter, or doubled along one axis
    for p in train:
        a, b = p['input'], p['output']
        H, W, h, w = len(a), len(a[0]), len(b), len(b[0])
        if not ((h, w) == (H, W) or (H - 2 <= h <= H and W - 2 <= w <= W) or (h, w) in ((H, 2 * W), (2 * H, W))
                or (h == w and h > max(H, W))):
            return
    tbg = _train_bg(train)
    nov = CR.novel_colour(train)
    decl = ([('novel', nov)] if nov is not None else []) + [('rank', k) for k in CR.RANKS]
    bgmodes = ['grid']
    if any(_bgc(p['input']) != tbg for p in train):
        bgmodes.append('train')
    # glued-mirror candidates: colours shared by every multi-colour object of the training inputs
    glued = []
    same48 = all(len(_comps(p['input'], _bgc(p['input']), 8)) == len(_comps(p['input'], _bgc(p['input']), 4))
                 for p in train)
    for conn in ((8,) if same48 else (8, 4)):
        shared = None
        for p in train:
            g = p['input']
            bg = _bgc(g)
            for comp in _comps(g, bg, conn):
                cols = {g[y][x] for y, x in comp}
                if len(cols) >= 2:
                    shared = cols if shared is None else shared & cols
        if shared:                            # role-bound mirror colours only (no literal from training)
            for mcb in ['shared', 'minority']:
                for pos in ('on', 'edge'):
                    glued.append(('glued', _pl_glued, (mcb, pos, conn)))
    # new background: input background cells all take one other colour where nothing was painted; that colour
    # must be named by one declared role over every pair (novel_colour, or rank_colour(k) of the input)
    tops = []
    for p in train:
        a, b = p['input'], p['output']
        if (len(a), len(a[0])) != (len(b), len(b[0])):
            tops = None
            break
        bg = _bgc(a)
        cnt = Counter(y for ra, rb in zip(a, b) for x, y in zip(ra, rb) if x == bg)
        top = cnt.most_common(1)[0][0] if cnt else bg
        if top == bg:
            tops = None
            break
        tops.append((a, bg, top))
    newbg = None
    if tops:
        newbg = next((s for s in decl if all(_rv(s, a, bg, None, {}) == top for a, bg, top in tops)), None)
    yielded = 0
    seen_sig = set()
    for bgmode in bgmodes:
        for kind, place, prm in PLACEMENTS[:8] + glued + PLACEMENTS[8:]:
            res_per = []
            ok = True
            for p in train:
                g = p['input']
                bg = tbg if bgmode == 'train' else _bgc(g)
                res = place(g, bg, prm)
                if res is None:
                    ok = False
                    break
                G, units, dr, dc = res
                if (len(G) - len(dr), len(G[0]) - len(dc)) != (len(p['output']), len(p['output'][0])):
                    ok = False
                    break
                res_per.append((bg, res))
            if not ok:
                continue
            # the rules for originals, mirror cells and strays do not depend on the images (nor on the ray)
            base = []
            for p, (bg, (G, units, dr, dc)) in zip(train, res_per):
                rm, cm = _maps(dr, dc, len(G), len(G[0]))
                base.append((G, bg, units, None, p['output'], rm, cm))
            origs = _induce_orig(base)
            interior_ok = all(_interior_possible(G, bg, units, out, newbg) for G, bg, units, _, out, _, _ in base)
            if not origs and not interior_ok:
                continue                      # no render can reproduce the training outputs
            mir = _induce_keep(base, 'mirror')
            strays = _induce_keep(base, 'strays')
            imgs0 = [_images(G, units) for G, bg, units, _, _, _, _ in base]
            for ray in ((None, 'pitch', 2, 1) if kind == 'grid' else (None,)):
                cases = []
                for (G, bg, units, _, out, rm, cm), im in zip(base, imgs0):
                    cases.append((G, bg, units, (im + _rays(G, units, ray)) if ray else im, out, rm, cm))
                renders = [('figure', o) for o in origs] + [('interior', 'keep')]
                imgs = list(islice(_induce_img(cases, decl), 2)) if origs else []
                for render, orig in renders:
                    if render == 'interior' and not interior_ok:
                        continue
                    for img, table in (imgs[:2] if render == 'figure' else [('keep', {})]):
                        P = {'img': img, 'table': dict(table), 'orig': orig, 'mirror': mir,
                             'strays': strays, 'render': render, 'newbg': newbg}
                        fn = _make(bgmode, tbg, place, prm, ray, P)
                        try:
                            if not _fits(cases, res_per, P):
                                continue
                        except Exception:
                            continue
                        sig = (kind, prm, ray, img, orig, render)
                        if sig in seen_sig:
                            continue
                        seen_sig.add(sig)
                        name = ("mirror_completion[bg=%s,place=%s:%s,ray=%s,img=%s,orig=%s,mirror=%s,strays=%s,"
                                "render=%s,newbg=%s]" % (bgmode, kind, prm, ray, img, orig, mir, strays, render,
                                                        _rname(newbg)))
                        cost = 1 + yielded
                        yield (name, cost, fn)
                        yielded += 1
                        if yielded >= 3:
                            return
                        break
                    else:
                        continue
                    break


FAMILIES = [fam]
